server:
  port: 9003
  servlet:
    context-path: /sgcb
spring:
  application:
    name: springboot-gateway-client-b
  ## spring boot admin
  boot:
    admin:
      client:
        url: http://127.0.0.1:8000
        instance:
          service-url: http://127.0.0.1:${server.port}
          managementUrl: http://127.0.0.1:${server.port}${server.servlet.context-path}/actuator
          health-url: http://127.0.0.1:${server.port}${server.servlet.context-path}/actuator/health
        username: admin
        password: admin
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
        group: DEFAULT_GROUP
        password: nacos
        username: nacos
        ip: 127.0.0.1
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env
  endpoint:
    health:
      show-details: always