server:
  port: 9003
  servlet:
    context-path: /sgcb
spring:
  application:
    name: springboot-gateway-client-b
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        password: nacos
        username: nacos
        namespace: public
        group: DEFAULT_GROUP
        ip: 127.0.0.1