server:
  port: 9001
spring:
  application:
    name: springboot-gateway-server
  config:
    import:
      - optional:nacos:springboot-gateway-server.yaml
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: public
        username: nacos
        password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
        ip: 127.0.0.1
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: springboot-gateway-client-a
          uri: lb://springboot-gateway-client-a
          predicates:
            - Path=/sgca/**
        - id: springboot-gateway-client-b
          uri: lb://springboot-gateway-client-b
          predicates:
            - Path=/sgcb/**
  ## spring boot admin
  boot:
    admin:
      client:
        url: http://127.0.0.1:8000
        instance:
          service-url: http://127.0.0.1:${server.port}
        username: admin
        password: admin
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
logging:
  level:
    org.springframework.cloud.*: debug
    com.alibaba.nacos: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env
  endpoint:
    health:
      show-details: always
gateway:
  routes:
    config:
      data-id: server-routes
      group: spb-gateway
      namespace: "b8806beb-bfd0-4eda-a1f4-5301cebf35cd"