server:
  port: 9001
spring:
  application:
    name: springboot-gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
        group: DEFAULT_GROUP
        password: nacos
        username: nacos
        ip: 127.0.0.1
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: springboot-gateway-client-a
          uri: lb://springboot-gateway-client-a
          predicates:
            - Path=/sgca/**
        - id: springboot-gateway-client-b
          uri: lb://springboot-gateway-client-b
          predicates:
            - Path=/sgcb/**
  ## spring boot admin
  boot:
    admin:
      client:
        url: http://127.0.0.1:8000
        instance:
          service-url: http://127.0.0.1:${server.port}
        username: admin
        password: admin
logging:
  level:
    org.springframework.cloud.*: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env
  endpoint:
    health:
      show-details: always