server:
  port: 8000

spring:
  application:
    name: admin-server
  security:
    user:
      name: "admin"
      password: "admin"
  boot:
    admin:
      ui:
        title: t-boot
      notify:
        mail:
          from: 544810359@qq.com
          to: 544810359@qq.com
  mail:
    host: smtp.qq.com
    username: 544810359@qq.com
    password: xx  # ?????
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
