server:
  port: 8200
spring:
  application:
    name: sentinel-client
  main:
    allow-bean-definition-overriding: true
  ## spring boot admin
  boot:
    admin:
      client:
        url: http://127.0.0.1:8000  # springboot admin server
        instance:
          service-url: http://127.0.0.1:${server.port}
        username: admin
        password: admin
  ## spring cloud
  cloud:
    inetutils:
      ignored-interfaces: eth.*
      preferred-networks: 127.0.0.1
    nacos:
      username: nacos
      password: nacos
      discovery:
        ip: 127.0.0.1
        server-addr: 127.0.0.1:8848   # nacos注册中心地址
        username: nacos
        password: nacos
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
    ## sentinel config
    sentinel:
      enabled: true # Sentinel自动化配置是否生效 默认：true
      eager: true   # 是否提前触发Sentinel初始化 默认：false
      transport:
        port: 8719 # 端口配置会在应用对应的机器上启动一个 Http Server，该 Server 会与 Sentinel 控制台做交互。比如 Sentinel 控制台添加了一个限流规则，会把规则数据 push 给这个 Http Server 接收，Http Server 再将规则注册到 Sentinel 中。
        dashboard: 127.0.0.1:8858   # sentinel-dashboard 控制台地址
        clientIp: 127.0.0.1   # 此配置的客户端IP将被注册到 Sentinel Server 端
  config:
    import:
      - optional:nacos:sentinel-client.yaml
#      datasource:
#        #================限流===============
#        flow:
#          nacos:
#            server-addr: 127.0.0.1:8848
#            #?sentinel????namespeace??
#            namespace: 6db12247-153b-4d0c-bef6-5c7c5e48faa3
#            #nacos??????dataId,??dataId???${spring.application.name}??????????????????????
#            data-id: ${spring.application.name}-flow-rules
#            #nacos??????groupId????????
#            group-id: SENTINEL_GROUP
#            #???????org.springframework.cloud.alibaba.sentinel.datasource.RuleType
#            rule-type: flow
#            #nacos???????
#            username: nacos
#            password: nacos
#        #================降级===============
#        degrade:
#          nacos:
#            server-addr: 127.0.0.1:8848
#            namespace: 6db12247-153b-4d0c-bef6-5c7c5e48faa3
#            data-id: ${spring.application.name}-degrade-rules
#            group-id: SENTINEL_GROUP
#            rule-type: degrade
#            username: nacos
#            password: nacos
#        #================系统规则===============
#        system:
#          nacos:
#            server-addr: 127.0.0.1:8848
#            namespace: 6db12247-153b-4d0c-bef6-5c7c5e48faa3
#            data-id: ${spring.application.name}-system-rules
#            group-id: SENTINEL_GROUP
#            rule-type: system
#            username: nacos
#            password: nacos
#        #================授权规则===============
#        authority:
#          nacos:
#            server-addr: 127.0.0.1:8848
#            namespace: 6db12247-153b-4d0c-bef6-5c7c5e48faa3
#            data-id: ${spring.application.name}-authority-rules
#            group-id: SENTINEL_GROUP
#            rule-type: authority
#            username: nacos
#            password: nacos
#        #================热点数据===============
#        param-flow:
#          nacos:
#            server-addr: 127.0.0.1:8848
#            namespace: 6db12247-153b-4d0c-bef6-5c7c5e48faa3
#            data-id: ${spring.application.name}-param-flow-rules
#            group-id: SENTINEL_GROUP
#            rule-type: param-flow
#            username: nacos
#            password: nacos

# ??Feign????????
#feign:
#  sentinel:
#    enabled: true